package Banco;

public class Interface extends javax.swing.JFrame {

    ContaCorrente cc = new ContaCorrente();
    ContaEspecial ce = new ContaEspecial();

    public Interface() {
        initComponents();
        txt_depositar.setVisible(false);
        txt_sacar.setVisible(false);
        btn_confirmDeposito.setVisible(false);
        btn_confirmSacar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rb_normal = new javax.swing.JRadioButton();
        rb_especial = new javax.swing.JRadioButton();
        btn_saldo = new javax.swing.JButton();
        btn_depositar = new javax.swing.JButton();
        btn_sacar = new javax.swing.JButton();
        txt_depositar = new javax.swing.JTextField();
        txt_sacar = new javax.swing.JTextField();
        btn_confirmDeposito = new javax.swing.JButton();
        btn_confirmSacar = new javax.swing.JButton();
        lbl_saldo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel1.setText("Banco Dinheiro SEM VIRUS PODE CONFIAR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(45, 16, 341, 18);

        buttonGroup1.add(rb_normal);
        rb_normal.setText("Cliente Normal");
        rb_normal.setActionCommand("Cliente Normal");
        rb_normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_normalActionPerformed(evt);
            }
        });
        getContentPane().add(rb_normal);
        rb_normal.setBounds(68, 46, 120, 21);

        buttonGroup1.add(rb_especial);
        rb_especial.setText("Cliente Especial");
        rb_especial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_especialActionPerformed(evt);
            }
        });
        getContentPane().add(rb_especial);
        rb_especial.setBounds(206, 46, 140, 21);

        btn_saldo.setText("Saldo");
        btn_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saldoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_saldo);
        btn_saldo.setBounds(33, 101, 72, 23);

        btn_depositar.setText("Depositar");
        btn_depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depositarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_depositar);
        btn_depositar.setBounds(154, 101, 84, 23);

        btn_sacar.setText("Sacar");
        btn_sacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sacarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sacar);
        btn_sacar.setBounds(278, 101, 84, 23);

        txt_depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_depositarActionPerformed(evt);
            }
        });
        getContentPane().add(txt_depositar);
        txt_depositar.setBounds(154, 147, 84, 22);
        getContentPane().add(txt_sacar);
        txt_sacar.setBounds(278, 147, 84, 22);

        btn_confirmDeposito.setText("Confirmar");
        btn_confirmDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmDepositoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirmDeposito);
        btn_confirmDeposito.setBounds(154, 187, 84, 23);

        btn_confirmSacar.setText("Confirmar");
        btn_confirmSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmSacarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirmSacar);
        btn_confirmSacar.setBounds(278, 187, 84, 23);
        getContentPane().add(lbl_saldo);
        lbl_saldo.setBounds(33, 147, 72, 22);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setText("GRATIS!!!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(236, 239, 126, 43);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LLLKKK.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 410, 300);

        setSize(new java.awt.Dimension(417, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_normalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_normalActionPerformed

    private void btn_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saldoActionPerformed
        if (rb_normal.isSelected()) {
            lbl_saldo.setText(String.valueOf(cc.getSaldo()));
        } else {
            ce.getSaldo();
            lbl_saldo.setText(String.valueOf(ce.getSaldo()));
        }

    }//GEN-LAST:event_btn_saldoActionPerformed

    private void rb_especialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_especialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_especialActionPerformed

    private void btn_depositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depositarActionPerformed
        txt_sacar.setVisible(false);
        btn_confirmSacar.setVisible(false);
        txt_depositar.setVisible(true);
        btn_confirmDeposito.setVisible(true);


    }//GEN-LAST:event_btn_depositarActionPerformed

    private void btn_confirmSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmSacarActionPerformed
        double saque = Double.valueOf(txt_sacar.getText());
        if (rb_normal.isSelected()) {
            cc.sacar(saque);
        } else {
            ce.sacar(saque);
        }
    }//GEN-LAST:event_btn_confirmSacarActionPerformed

    private void txt_depositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_depositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_depositarActionPerformed

    private void btn_sacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sacarActionPerformed
        txt_depositar.setVisible(false);
        btn_confirmDeposito.setVisible(false);
        txt_sacar.setVisible(true);
        btn_confirmSacar.setVisible(true);


    }//GEN-LAST:event_btn_sacarActionPerformed

    private void btn_confirmDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmDepositoActionPerformed
        double deposito = Double.valueOf(txt_depositar.getText());
        if (rb_normal.isSelected()) {
            cc.depositar(deposito);
        } else {
            ce.depositar(deposito);
        }

    }//GEN-LAST:event_btn_confirmDepositoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmDeposito;
    private javax.swing.JButton btn_confirmSacar;
    private javax.swing.JButton btn_depositar;
    private javax.swing.JButton btn_sacar;
    private javax.swing.JButton btn_saldo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_saldo;
    private javax.swing.JRadioButton rb_especial;
    private javax.swing.JRadioButton rb_normal;
    private javax.swing.JTextField txt_depositar;
    private javax.swing.JTextField txt_sacar;
    // End of variables declaration//GEN-END:variables
}
